name: "tocgen"
description: "Automatically generate and update Markdown Tables of Contents between specified markers."
author: "Evoteum <dev@evoteum.com>"

runs:
  using: "docker"
  image: "docker://quay.io/evoteum/tocgen:latest"

branding:
  icon: "list"
  color: "blue"